<?php

$lang = array(

    //CP
    'pro_module_name' => 'ExpressionEngine Pro',
    'pro_settings_updated' => 'Les réglages ont été mis à jour',
    'branding' => 'Image de Marque',
    'branding_settings' => 'Image de Marque',
    'login_logo' => 'Logo à afficher sur l\'écran de connexion',
    'login_logo_desc' => 'Choisissez une image; la largeur maximum recommandée est de 400px',
    'favicon' => 'Favicon',
    'favicon_desc' => 'Fichiers recommandés .ico ou 32x32 .png ',
    'license' => 'Licence',
    'pro_license_number' => 'Numéro de licence d\'ExpressionEngine Pro',
    'pro_license_number_desc' => 'Vous devez posséder un numéro de licence valide pour utiliser cet add-on',
    'frontedit' => 'Edition en Avant-Plan',
    'frontedit_settings' => 'Réglages d\'édition en Avant-Plan',
    'enable_dock' => 'Activer le Dock?',
    'enable_dock_desc' => 'Active le Dock sur l\'Avant-Plan.',
    'enable_frontedit' => 'Activer l\'édition sur l\'Avant-Plan?',
    'disable_frontedit' => 'Désactiver l\'édition sur  l\'Avant-Plan?',
    'enable_frontedit_desc' => 'Active la gestion  de contenus sur l\'Avant-Plan.',
    'automatic_frontedit_links' => 'Activer automatiquement les liens d\'édition sur l\'Avant-Plan?',
    'automatic_frontedit_links_desc' => 'Crée automatiquement des liens pour éditer les champs d\'entrées sur l\'Avant-Plan.',
    'pro_settings' => 'Réglages Pro',
    'general_pro_settings' => 'Réglages Pro',
    'enable_frontedit_tmpl_desc' => 'Active la gestion de contenus sur l\'Avant-Plan de ce modèle',
    'enable_entry_cloning' => 'Activer le clonage des entrées?',
    'enable_entry_cloning_desc' => 'Met en marche la fonctionnalité "Cloner vers la Nouvelle Entrée". Peut être désactivée selon le canal ciblé.',
    'enable_frontedit_field_desc' => 'Active la gestion de contenus de l\'Avant-Plan pour ce champ',
    'cookie_settings' => 'Réglages des Cookies',
    'cookie_title' => 'Titre de Cookie',
    'cookie_name' => 'Nom de Cookie',
    'cookie_provider' => 'Fournisseur de Cookie',
    'cookie_lifetime' => 'A vie',
    'cookie_title_desc' => 'Titre de cookie tel qu\'affiché dans les balises de modèles',
    'cookie_description' => 'Description de Cookie',
    'cookie_description_desc' => 'Description de Cookie telle qu\'affichée dans les balises de modèles',
    'cookie_lifetime_desc' => 'Nombre de secondes, <code>0</code> pour les cookies de session',

    'necessary_cookies' => 'Cookies de nécessité',
    'functionality_cookies' => 'Cookies de fonction',
    'performance_cookies' => 'Cookies de performance',
    'targeting_cookies' => 'Cookies de ciblage',

    // Pro Cookies
    'cookie_frontedit' => 'Edition sur l\'Avant-Plan',
    'cookie_frontedit_desc' => 'Détermine si les fonctionnalités de l\'édition sur l\'Avant-Plan d\'ExpressionEngine doivent être activées.',

    'export_consent_log' => 'Exporter les journaux d\'audit de consentement',
    'exported_consent_log' => 'Les journaux d\'audit de consentement ont été exportés',

    //Dock
    'edit_in_full_form' => 'Editer l\'entrée complète…',
    'modal_is_dirty_close_confirmation' => 'Les données ont peut-être changé. Etes-vous sûr(e) de vouloir fermer cette fenêtre?',
    'edit_mode' => 'Editer le Mode',
    'view_cp' => 'Visualiser le Tableau de Bord',
    'hide_dock' => 'Cacher le Dock',
    'save' => 'Sauvegarder',
    'cancel' => 'Annuler',
    'save_without_reload' => 'Sauvegarder sans rechargement',

    'prolet_does_not_exist' => 'Ce Prolet n\'existe pas',
    'no_prolets_available' => 'Aucun Prolet n\'est disponible pour cet add-on',
    'prolet_action_does_not_exist' => 'L\'action du Prolet n\'existe pas',
    'prolet_did_not_return_valid_data' => 'Le Prolet n\'a retourné aucune donnée valide',

    'mfa' => 'Authentification Multi-Facteurs',
    'enable_mfa' => 'Autoriser l\'Authentification Multi-Facteurs?',
    'enable_mfa_desc' => 'Active la confirmation de l\'authenticité de l\'utilisateur en utilisant une application sur un appareil mobile',
    'jump_mfa' => 'Mon Profil &raquo; <b>Authentification Multi-facteurs</b>',
    'disable' => 'Désactiver',
    'disable_mfa' => 'Désactiver l\'authentification Multi-Facteurs?',
    'reset_mfa' => 'Réinitialiser l\'Authentification Multi-Facteurs?',
    'mfa_save_error_desc' => 'Impossible de sauvegarder la préférence d\'Authentification Multi-Facteurs',
    'mfa_disabled' => 'L\'Authentification Multi-Facteurs est désactivée',
    'mfa_disabled_desc' => 'Vous pouvez maintenant vous connecter en utilisant seulement votre identifiant et votre mot de passe',
    'mfa_enabled' => 'L\'Authentification Multi-Facteurs est activée',
    'mfa_enabled_desc' => 'Vous serez désormais astreint(e) à saisir une code de vérification unique à chaque connexion',
    'existing_password_mfa_reset_desc' => 'Vous devez saisir votre mot de passe actuel pour réinitialiser l\'Authentification Multi-facteurs',
    'mfa_qr_code' => 'QR Code',
    'mfa_qr_code_desc' => 'Scannez ce code en utilisant l\'application d’Authentification Multi-facteurs disponible sur votre appareil mobile, telles que Authy, Google Authenticator ou LastPass',
    'mfa_backup_code' => 'Code de sauvegarde',
    'backup_mfa_code' => 'Code de sauvegarde MFA',
    'mfa_backup_code_desc' => 'Ce code peut-être utilisé pour réinitialiser l\'Authentification Multi-Facteurs si vous perdez votre appareil',
    'mfa_backup_warning_desc' => 'Conservez ce code en lieu sûr. Il ne vous sera plus de nouveau affiché ',
    'mfa_reset_success' => 'Réinitialisation de l\'Authentification Multi-Facteurs',
    'mfa_reset_success_message' => 'Il vous sera nécessaire de scanner le  QR code et de le valider de nouveau pour l\'utilisation de l\'Authentification Multi-Facteurs',
    'mfa_wrong_backup_code' => 'Code de sauvegarde erroné',
    'mfa_wrong_backup_code_desc' => 'Le code que vous avez saisi est non valide',
    'require_mfa' => 'Requérir l\'Authentification Multi-Facteurs',
    'require_mfa_desc' => 'Quand elle est confirmée, tous les membres rattachés à ce Rôle seront astreints à mettre en place l\'authentification multi-facteurs',
    'mfa_required' => 'L\'Authentification Multi-Facteurs est requise',
    'mfa_required_desc' => 'L\'administration du site requiert que vous activiez et que vous mettiez en place l\'Authentification Multi-Facteurs pour votre compte',
    'mfa_required_login_as' => 'Vous devez avoir utilisé l\'authentification à plusieurs facteurs pour vous connecter en qualité de ce membre',
	'mfa_code' => 'Code de vérification',
    'mfa_code_desc' => 'Généré par l\'application affectée à l\'Authentification Multi-Facteurs sur votre appareil mobile',
    'mfa_wrong_code' => 'Code erroné',
    'mfa_wrong_code_desc' => 'Le code de vérification que vous avez saisi n\'est pas valide',
    'mfa_not_available' => 'L\'Authentification Multi-Facteurs n\'est pas disponible',
    'mfa_wrong_user_desc' => 'L\'Authentification Multi-Facteurs ne peut être configurée que pour l\'utilisateur connecté',
    'pro_license_error' => 'Erreur de licence ExpressionEngine Pro.',
    'pro_license_error_trial' => 'Puisque ce site possède plusieurs membres, il lui est requis une licence payante. Merci d\'acheter une licence avant le lancement. Merci!',
    'pro_license_error_na' => 'L\'état de la Licence ExpressionEngine Pro est inconnu.',
    'pro_license_error_invalid' => 'La Licence Pro d\'ExpressionEngine Pro n\'est pas valide pour ce site.',
    'pro_license_error_expired' => 'La Licence Pro d\'ExpressionEngine a expiré.',

    'pro_license_check_instructions' => 'Puisque ce site possède plusieurs membres, il lui sera requis une licence payante. %s.<br><br>Merci de vérifier la <a href="%s">Clé de licence du site</a>  et rendez vous à la section <a href="https://expressionengine.com/store/licenses" target="_blank">Licences</a> sur ExpressionEngine.com',

    'pro_license_check_trial_instructions' => '%s<br><br>Merci de vérifier votre<a href="%s">Clé de licence de site</a> et rendez vous à la section <a href="https://expressionengine.com/store/licenses" target="_blank">Licences</a> sur ExpressionEngine.com',
	'pencil_icon' => 'Icône de crayon',
    'drag_handle_icon' => 'Faire glisser l\'icône de la poignée',

);
