<?php

$lang = array(

    'cp_module_settings_title'  => 'Réglages de Module',
    'cp_channel_settings_title' => 'Réglages de canal',
    'add'               => 'Ajouter',
    'edit'              => 'Editer',
    'cancel'            => 'Annuler',
    'delete'            => 'Supprimer',
    'page'              => 'Page',
    'pages'             => 'Pages',
    'entries'           => 'Entrées',
    'asset'             => 'Atout',
    'assets'            => 'Atouts',
    'listing'           => 'Liste',
    'listings'          => 'Listes',
    'channel'           => 'Canal',
    'type'              => 'Type',
    'structure_uri'     => 'Structure URI',
    'structure'         => 'Structure',
    'no_structure'      => '<ol>
                                <li>Affecter les canaux et les modèles à utiliser dans <a href="%{link_to_settings}">Réglages de Canaux</a></li>
                                <li>Utiliser le Contenu > Publier l\'onglet pour créer vos premières pages de haut niveau.
                            </ol>',
    'no_weblogs'        => 'Merci de créer un Canal avant d\'utiliser Structure',
    'groups'            => 'Groupe',
    'no_roles'         => 'Aucun accès à Structure n\'a encore été accordé à un Rôle de Membre',
    'no_roles_add'     => 'Gérer l\'accès des Rôles de Membres',
    'roles'            => 'Rôles',
    'role'            => 'Rôle',
    'create_page'       => 'Créer une Nouvelle Page',
    'choose_page_type'  => 'Choisir un Type de Page',
    'view_page'         => 'Visualiser la Page',
    'none'              => 'Aucun(e)',
    'select_template'   => 'Sélectionner un modèle',
    'select_page_type'  => 'Sélectionner un type de page',
    'getting_started'   => 'Commencer',
    'template'          => 'Modèle de Structure',
    'parent'            => 'Parent(e)',
    'view_page'         => 'Visualiser la Page',
    'listing_channel'   => 'Lister les Canaux',
    'structure_deleted' => 'Les données de Structure ont été supprimées',
    'invalid_page_name' => 'Un nom de Page non valide a été saisi',
    'invalid_template'  => 'Vous devez sélectionner un modèle valide pour afficher cette page.',
    'invalid_uri'       => 'Merci d\'entrer une URI valide.',
    'default_template'  => 'Modèle par défaut',
    'no_default'        => 'Aucun défaut',
    'settings_updated'  => 'Réglages mis à jour',
    'structure_deleted' => 'Info de Structure supprimée',
    'settings_save'     => 'Sauvegarder',
    'settings_cancel'   => 'Annuler',
    'settings_perms'    => 'Permissions',
    'unmanaged'         => 'Non géré(e-s)',
    'cancel'            => 'Annuler',
    'delete_page'       => 'Supprimer la Page',
    'all_pages'         => 'Toutes les pages',
    'system_pref'       => 'Préférence Système',
    'system_prefs'      => 'Préférences Système',
    'prefs'             => 'Préférences',

    'show_in_page_selector'     => 'Afficher dans le sélecteur de page',
    'content_preferences'       => 'Préférences de contenu',
    'cp_preferences'            => 'Préférences de Tableau de Bord',
    'settings_enable_picker'    => 'Activer le sélecteur de type de page (canal)?',
    'ui_add_page'               => 'Ajouter Page',
    'ui_expand_all'             => 'Elargir Pages',
    'ui_collapse_all'           => 'Réduire Pages',
    'ui_add_child_page'         => 'Ajouter une Page enfant',
    'ui_add_listing'            => 'Joindre une liste à cette page?',
    'setting_redirect_login'    => 'Rediriger vers Structure lors de la Connexion',
    'setting_redirect_publish'  => 'Rediriger vers Structure au moment de publier/sauvegarder une entrée',
    'split_assets'              => 'Faire de chaque entrée un atout unique (pas de Ajouter/Editer)',
    'hide_hidden_templates'     => 'Masquer les modèles cachés avec l\'onglet publier/editer',

    'setting'                       => 'Réglage',
    'structure_settings'            => 'Réglages',
    'duplicate_page_uri'            => 'Dupliquer URI de Page',
    'structure_homepage'            => 'Page d\'accueil de Structure',
    'settings_default_tpl'          => 'Modèles de Canaux par défaut',
    'structure_module_name'         => 'Structure',
    'structure_delete_confirm'      => 'Etes-vous sûr(e) de vouloir <strong>supprimer cette page</strong>?<br /><br /><strong>Notez:</strong> Supprimer une page ne supprime pas les contenus des entrées.<br /><br />',
    'structure_delete_question'     => 'Etes-vous sûr(e) de vouloir supprimer les pages sélectionnées? Notez: Supprimer une page ne supprime pas les contenus des entrées.',
    'structure_module_description'  => 'Créer des pages, générer la  navigation, gérer le contenu à travers une une interface simple et construire des sites robustes plus rapidement que jamais.',
    'show_view_page_links'          => 'Montrer les liens "Visualisation de Page" dans l\'arborescence de la page',
    'show_page_statuses'            => 'Montrer les Statuts de Page',
    'show_page_type'                => 'Montrer Type de Page',
    'show_global_add_page_button'   => 'Montrer le bouton global "Ajouter une Page"',
    'member_group_permission'       => 'Permissions de Membres',
    'edit_an_entry_on_this_page'    => 'Editer une entrée sur cette page',
    'add_an_entry_on_this_page'     => 'Ajouter une entrée sur cette page',
    'edit_group_page_title'         => 'Editer Groupe Nav',
    'delete_group_page_title'       => 'Supprimer Groupe Nav',

    'access_control_panel'          => 'Peut accéder au tableau de bord',
    'access_publish'                => 'Part accéder à publier',
    'access_edit'                   => 'Peut accéder à éditer',
    'access_structure'              => 'Peut accéder à Structure',

    'settings_manage'               => 'Gérer',
    'settings_reorder'              => 'Réorganiser',
    'settings_options'              => 'Options',
    'settings_n_a'                  => 'n/a',
    'channel_settings_none'         => 'Vous n\'avez ajouté encore aucun canal',
    'channel_settings_add'          => 'Ajouter des Canaux',
    'confirm_delete_channels'       => 'Etes-vous sûr(e) de vouloir supprimer ces canaux de Structure?',

    'setting_trailing_slash' => "Ajouter une Barre oblique finale aux URL de pages?",

    // entry's structure tab
    'tab_parent_entry'      => 'Entrée parente de Structure ',
    'tab_page_url'          => 'Page URL de Structure',
    'tab_listing_url'       => 'Liste URL de Structure ',
    'tab_listing_option'    => 'Liste de Structure ',

    'ootb_title'                        => 'Commencer avec Structure',
    'ootb_intro'                        => 'Les sections ci-dessous vous aideront à en savoir plus sur Structure et ses fonctionnalités',
    'ootb_add_first_page'               => 'Ajouter votre première Page',
    'ootb_title_page_types'             => 'Types de Pages',
    'ootb_copy_page_types'              => 'Structure a trois types de pages qui vous aideront à construire votre site',
    'ootb_read_page_types'              => 'Lire la suite au sujet de ces types de pages',
    'ootb_title_channel_settings'       => 'Réglages de canaux',
    'ootb_copy_channel_settings'        => 'Contrôler les canaux qu\'utilise Structure et quel est leur type',
    'ootb_read_channel_settings'        => 'Lire la suite à propos des réglages de canaux',
    'ootb_title_module_settings'        => 'Réglages de Module',
    'ootb_copy_module_settings'         => 'Paramètres de création et permissions de base des membres pour l\'édition',
    'ootb_read_module_settings'         => 'Lire la suite à propos des réglages de module',
    'ootb_title_nav_tag'                => 'Onglet de navigation',
    'ootb_copy_nav_tag'                 => 'L\'onglet de navigation construit de manière dynamique toute votre navigation à votre place',
    'ootb_read_nav_tag'                 => 'Lire la suite à propos de l\'onglet de navigation',

    'ootb_message_channel_settings'         => 'Vous devez affecter des canaux que Structure peut utiliser avant d\'ajouter des pages',
    'ootb_message_channel_settings_read'    => 'Lire la suite à propos des réglages de canaux',

    'ootb_message_no_channel_settings'          => 'Vous devez affecter des canaux à Structure afin d\'ajouter des pages',
    'ootb_message_no_channel_settings_link'     => 'Ajouter des canaux à Structure',

    'ootb_message_channel_settings_go'          => 'Vous êtes prêt(e) à ajouter des pages',

    // 'module_name'            => 'Structure',
    'page_settings'     => ' Configuration de Structure',

    // Validation System
    'validation' => 'Validation',
    'structure_validation' => ' Validation de Structure',
    'structure_validation_desc' => 'Ceci compare l’index possédé par Structure comparativement à ce qu\'ExpressionEngine considère l\'index que <em>devrait</em> employer Structure.',
    'total_entries' => 'Total Entrées',
    'total_missing_from' => 'Total manquant depuis',
    'ee_url_routing' => 'Routage URL EE ',
    'ee' => 'EE',
    'structure_listings' => 'Listes Structure',
    'note_colon' => 'NOTEZ:',
    'listings_auto_fix' => 'Les listes ne peuvent pas être corrigées automatiquement.',
    'please_edit_listings_individually' => 'Merci d\'éditer les entrées de listes individuellement.',
    'errored_entries' => 'Entrées erronées',
    'errored_entries_desc' => 'Entrées qui ne correspondent pas au <br />Routage entre Structure et EE',
    'expressionengine' => 'ExpressionEngine',
    'expressionengine_desc' => 'Vos entrées actuelles',
    'expressionengine_url_routing' => 'Routage URL<br />ExpressionEngine',
    'expressionengine_url_routing_desc' => 'Remplacé par Structure<br /><br />Peut se synchroniser<br />si une erreur est<br />rencontrée en<br />sauvegardant une entrée de canal',
    'structure_desc' => 'Une copie plus fiable<br />de ce qui se trouve au sein<br />du routage URL<br />d\'ExpressionEngine',
    'entry_id' => 'ID entrée',
    'listing_cid' => 'Liste CID:',
    'listing_entry' => 'Liste Entrée',
    'exists' => 'Existe',
    'missing' => 'MANQUANT',
    'choose_action' => 'Choisir Action',
    'use_url_routing' => 'Utiliser le Routage URL',
    'use_structure' => 'Utiliser Structure',
    'what_this_does' => '<strong>Ce que cela fait</strong>',
    
    'what_this_does_url_routing' => '<strong>Supprime</strong><br />les entrées du<br /><strong>Routage URL EE</strong><br />manquantes depuis<br /><strong>Structure</strong>',
    'what_this_does_structure' => '<strong>Insère</strong><br />les entrées de <br /> <strong>Structure</strong><br />de retour vers<br /> <strong>le Routage URL EE</strong>',
    'what_is_the_result' => '<strong>Ce qui en résulte</strong>',
    'what_is_the_result_url_routing' => 'Vous obtiendrez <strong>moins</strong><br />d\'entrées dans Structure.',
    'what_is_the_result_structure' => 'Vous obtiendrez <strong>le même</strong><br />nombre d\'entrées dans Structure',
    'no_corrupt_entries' => 'Pas d\'entrées corrompues!',
    'duplicate_left_rights' => 'Dupliquer les valeurs Gauches et/ou Droites.',
    'duplicate_lefts' => 'Dupliquer à Gauche:',
    'duplicate_rights' => 'Dupliquer à Droite:',
    
    'structure_restore_previous_nav' => 'Votre arborescence de Structure semble corrompue. Merci de restaurer l\'état de l\'historique précédent en cliquant sur le lien Historique.',
    'no_orphaned_entries' => 'Pas d\' Entrées orphelines ni de Positions dupliquées Gauche/Droite!',
    'url_mismatches' => 'URL non concordantes',
    'url_mismatches_desc' => 'Les entrées suivantes ont des URL non concordantes entre le Routage URL EE et Structure et peuvent causer des problèmes avec le chargement de pages de votre site et sur le choix des URL utilisées par vos liens.',
    'ee_url_routing_url' => 'URL de Routage URL EE',
    'structure_url' => 'URL Structure',
    'no_url_mismatches' => 'Pas de discordances entre le Routage URL EE et Structure!',
    'url_duplicates' => 'Doublons URL',
    'url_duplicates_desc' => 'Les entrées suivantes ont une URL Structure en doublon ce qui peut causer des problèmes avec le chargement de pages de votre site et sur le choix des URL utilisées par vos liens.',
        
    'no_duplicate_urls' => 'Pas d\'URL Structure en doublon!',
    'template_id' => 'ID Modèle',
    'template_id_validation' => 'Validation ID de Modèle',
    'template_id_validation_desc1' => 'Les modèles référents des entrées suivantes qui n\'existent pas dans votre installation  ExpressionEngine.',
    'template_id_validation_desc2' => 'Vous devrez éditer vos entrées et modifier le modèle associé sur l\'onglet Structure.',
    'no_template_id_errors' => 'Pas d\'erreurs d\'ID de modèles!',
    'no_structure_missing_entries' => 'Aucune entrée manquante dans Structure!',
    'update_msm_listing_site_id' => 'Mettre à jour la liste des ID de Sites MSM',
    
    'update_msm_listing_site_id_desc' => 'Cela fera une boucle à travers les canaux ExpressionEngine existants et mettra à jour les canaux de Structure pour s\'assurer que les ID de site correspondent.',
    
    'structure_missing_entries' => 'Entrées manquantes de Structure',
    
    'structure_missing_entries_desc' => 'Cela affichera toutes les entrées des canaux gérés par Structure qui ne sont PAS encore actuellement dans Structure.<br /><br /><strong>NOTEZ:</strong> Cela n\'est pas nécessairement une erreur! Si vous avez des entrées dans les canaux gérés par Structure que vous ne souhaitez pas intégrer dans Structure, vous pouvez les ignorer ci-dessous.',
    'show_entries_missing_from_structure' => 'Afficher les entrées Manquantes de Structure',
    
    // Reordering
    'structure_reorder_invalid_timestamp' => "Le réagencement a échoué\n\nVotre arborescence de Structure semble obsolète.\n\nQuelqu\'un d\'autre peut être en train d\'éditer ou vous avez peut-être un autre onglet avec une arborescence de Structure plus récente.\n\nVeuillez actualiser et réessayer de réagencer à nouveau.",
    'structure_reorder_invalid_data' => "Le réagencement a échoué\n\nDonnées de page non valides",
    'structure_reorder_invalid_site_id' => "Echec du réagencement\n\nID de site non valide",

    // nav history
    'history' => 'History',
    'site_id'              => 'ID Site',
    'note'                 => 'Note',
    'date'                 => 'Date',
    'current'              => 'Actuel?',
    'restore'              => 'Restaurer',
    'status'               => 'Statut',
    'yes'                  => 'Oui',
    'no'                   => 'Non',
    'structure_version'    => 'Version de Structure',
    'no_history_entries'   => 'Il n\'y a pas encore d\'historique d\'entrées. Commencez à utiliser Structure pour générer automatiquement des entrées.',
    'skipped'              => 'Laisser tomber',

    //
    '' => ''
);
