<?php

$lang = array(

'rte_module_name' => 'Éditeur de texte enrichi',
'rte_module_description' => 'Active le mode d\'édition en texte enrichi dans les zones de texte',

// Headings
'nav_rte_settings' => 'Éditeur de texte enrichi',
'nav_rte_settings_short_desc' => 'Gérer les outils et les jeux d\'outils de l\'éditeur de texte enrichi',
'rte_settings' => 'Préférences de site',
'rte_prefs' => 'Préférences de l\'éditeur de texte enrichi',
'toolsets' => 'Jeux d\'outils',
'tools' => 'Outils',
'create_new_toolset' => 'Créer un nouveau jeu d\'outils',
'edit_toolset' => 'Éditer le jeu d\'outils',
'edit_my_toolset' => 'Éditer mon jeu d\'outils',
'my_toolset'	=> 'Mon jeu d\'outils',

// Snippets
'no' => 'Non',
'yes' => 'Oui',
'enabled' => 'Activé',
'enable_button' => 'Activer',
'disabled' => 'Désactivé',
'disable_button' => 'Désactiver',
'delete' => 'Supprimer',
'toolset' => 'Jeu d\'outils',
'tool' => 'Outil',
'cancel' => 'Annuler',
'enable_rte' => 'Activer l\'éditeur de texte enrichi',
'disable_rte' => 'Désactiver l\'éditeur de texte enrichi',

// Flashes
'settings_saved' => 'Vos paramètres pour l\'éditeur de texte enrichi ont été enregistrés.',
'settings_not_saved' => 'Vos paramètres pour l\'éditeur de texte enrichi n\'ont pas pu être enregistrés. Merci de ré-essayer.',
'settings_saved' => 'Vos préférences pour l\'éditeur de texte enrichi ont été enregistrées.',
'settings_not_saved' => 'Vos préférences pour l\'éditeur de texte enrichi n\'ont pas pu être enregistrées. Merci de ré-essayer.',
'toolset_deleted' => 'Jeu d\'outils supprimé avec succès.',
'toolset_not_deleted' => 'Le jeu d\'outils n\'a pas pu être supprimé.',
'toolset_edit_failed' => 'Le jeu d\'outil n\'a pas pu être ouvert à fin d\'édition.',
'toolset_updated' => 'Jeu d\'outils mis à jour',
'toolset_update_failed' => 'La mise à jour du jeu d\'outils a échouée. Merci de ré-essayer.',
'tool_updated' => 'Outil mis à jour',
'tool_update_failed' => 'La mise à jour de l\'outil a échouée. Merci de ré-essayer.',
'valid_url_required' => 'une URL valide est requise.',
'name_required' => 'Le nom du jeu d\'outils est requis.',
'unique_name_required' => 'Le nom du jeu d\'outils doit être unique.',

// Labels
'enable_rte_globally' => 'Activer l\'éditeur de texte enrichi ?',
'enable_rte_in_forum' => 'Activer l\'éditeur de texte enrichi pour les forums ?',
'default_toolset' => 'Jeu d\'outils par défaut',
'default_toolset_details' => 'Affiché pour les utilisateurs qui n\'auraient pas créé le leur ou choisi un autre.',
'toolset_name' => 'Nom du jeu d\'outils',
'available_tools' => 'Outils disponibles (non utilisés)',
'tools_in_toolset' => 'Dans ce jeu d\'outils',
'toolset_builder_label' => 'Quels outils devraient être disponibles dans ce jeu d\'outils ?',
'toolset_builder_instructions' => 'Sélectionnez un ou plusieurs outils et glissez-les à l\'emplacement désiré.',
'enable_rte_myaccount' => 'Activer l\'éditeur de texte enrichi ?',
'enable_rte_for_field' => 'Activer l\'éditeur de texte enrichi ?',
'rte_image_caption'	=> 'Légende d\'image :',
'rte_center_error' => 'Vous ne pouvez pas centrer un élément habillé',
'url' => 'URL',
'title' => 'Titre',
'relationship' => 'Relations',
'selection_error' => 'Sélectionnez d\'abord du texte ou des images.',

// Tool names (based on class name)
'blockquote_rte' 	=> 'Citer',
'bold_rte' 			=> 'Gras',
'headings_rte' 		=> 'Titrage',
'image_rte' 		=> 'Image',
'italic_rte' 		=> 'Italique',
'link_rte' 			=> 'Lien',
'ordered_list_rte' 	=> 'Liste ordonnée',
'preferences_rte' 	=> 'Préférences',
'strip_tags_rte' 	=> 'Effacer le formatage',
'underline_rte' 	=> 'Souligner',
'unordered_list_rte'=> 'Liste à puces',
'view_source_rte' 	=> 'Voir le code',

// Tool misc
'make_bold' => 'Gras',
'remove_bold' => 'Non gras',
'make_italics' => 'Mettre en italique',
'remove_italics' => 'Enlever l\'italique',
'make_underline' => 'Souligner',
'remove_underline' => 'Enlever le souligné',
'make_ul' => 'Liste à puces',
'remove_ul' => 'Enlever la liste à puces',
'make_ol' => 'Liste ordonnée',
'remove_ol' => 'Enlever la liste ordonnée',
'make_blockquote' => 'Citer',
'remove_blockquote' => 'Enlever la citation',
'link' => 'Lien',
'add_link' => 'Ajouter un lien',
'update_link' => 'Mettre à jour le lien',
'remove_link' => 'Enlever le lien',
'external_link' => 'Lien externe',
'view_code' => 'Voir le code',
'view_content' => 'Voir le contenu',
'strip_tags' => 'Effacer le formatage',
'paragraph' => 'paragraphe',
'heading_1' => 'titre 1',
'heading_2' => 'titre 2',
'heading_3' => 'titre 3',
'heading_4' => 'titre 4',
'heading_5' => 'titre 5',
'heading_6' => 'titre 6',
'img_add' => 'Image',
'img_remove' => 'Enlever l\'image',
'img_align_left' => 'Aligner à Gauche',
'img_align_center' => 'Aligner au Centre',
'img_align_right' => 'Aligner à Droite',
'img_wrap_left' => 'Habiller à Gauche',
'img_wrap_none' => 'Séparer l\'image du texte',
'img_wrap_right' => 'Habiller à Droite',

''=>''
);

/* End of file rte_lang.php */
/* Location: ./system/expressionengine/language/french/rte_lang.php */