<?php

$lang = array(
	'safecracker_module_name' => 'SafeCracker',
	'safecracker_settings' => 'Paramètres',
	'safecracker_extension_not_installed' => 'L\'extension SafeCracker n\'est pas installée.',
	'safecracker_extensions_disabled' => 'Merci d\'activer les extensions avant installation.',
	'safecracker_ee_version' => 'Votre version d\'ExpressionEngine n\'est pas compatible avec SafeCracker. Vous devez avoir au minimum la version 2.1.2.',
	'safecracker_weblog_settings' => 'Paramètres de canal',
	'safecracker_module_description' => 'Une meilleure façon de créer des formulaires de saisie autonomes.',
	'safecracker_module_channel' => 'Canal',
	'safecracker_require_captcha' => 'Exiger les Captcha pour les invités ?',
	'safecracker_allow_guests' => 'Autoriser les invités à effectuer des saisies ?',
	'safecracker_logged_out_member_id' => 'Définir l\'ID de membre à utiliser pour les invités.',
	'safecracker_logged_out_member_id_note' => 'Entrez ici une ID de membre à activer. Laissez à blanc pour désactiver. Si activé, les utilisateurs non connectés pourront saisir dans ce canal. Leurs saisies seront enregistrées avec cette ID de membre en tant qu\'ID d\'auteur. Pensez à définir toutes les autorisations nécessaires pour le groupe de membre qui correspond à cette ID de membre.',
	'safecracker_override_status' => 'Statut par défaut',
	'safecracker_override_status_note' => 'Sélectionnez un statut par défaut. Ce paramètre remplacera tout statut soumis par le formulaire de saisie.',
	'safecracker_select_member' => 'Sélectionner un membre',
	'safecracker_more_members' => 'Plus de membres&hellip;',
	'safecracker_select_member_group' => 'Sélectionner un groupe de membre',
	'safecracker_filter_member_list' => 'Filtrer la liste de membres',
	'safecracker_filter_member_list_member_group' => 'Par groupe de membre :',
	'safecracker_filter_member_list_keyword' => 'Par mot clef :',
	'safecracker_list_fieldtypes' => 'Liste des types de champ installés',
	'safecracker_fieldtype_name' => 'Nom',
	'safecracker_fieldtype_short_name' => 'Nom court',
	'safecracker_no_channel' => 'Aucun canal n\'a été indiqué.',
	'safecracker_invalid_channel' => 'Le canal indiqué est invalide.',
	'safecracker_invalid_guest_member_id' => 'L\'ID de membre fournie afin d\'être utilisée pour les soumissions des invités est invalide.',
	'safecracker_require_entry' => 'Vous devez indiquer une saisie valide à éditer.',
	'safecracker_author_only' => 'Vous n\'êtes pas l\'auteur de cette saisie.',
	'yes' => 'Oui',
	'no' => 'Non',
	'safecracker_valid_ee_date' => 'La %s que vous avez soumise n\'était pas formattée correctement (année-mois-jour heure:minute)',
	'safecracker_no_data' => 'Aucune donnée.',
	'curl_not_installed'	=> 'La librairie cURL pour PHP doit être installée pour pouvoir traiter les formulaires envoyés à des tierces parties hors site.',

	/* rules */
	'form_decryption_failed' => 'Le décryptage des paramètres de formulaire a échoué.',
	'required' => 'Le champ %s est requis.',
	'isset' => 'Le champ %s doit avoir une valeur.',
	'valid_email' => 'Le champ %s doit contenir une adresse email valide.',
	'valid_emails' => 'Le champ %s doit contenir des adresses email toutes valides.',
	'valid_url' => 'Le champ %s doit contenir une URL valide.',
	'valid_ip' => 'Le champ %s doit contenir une adresse IP valide.',
	'min_length' => 'Le champ %s doit faire au moins %s caractères de long.',
	'max_length' => 'Le champ %s ne peut dépasser %s caractères de long.',
	'exact_length' => 'Le champ %s doit faire exactement %s caractères de long.',
	'alpha' => 'Le champ %s ne peut contenir que des caractères alphabétiques.',
	'alpha_numeric' => 'Le champ %s ne peut contenir que des caractères alphanumeriques.',
	'alpha_dash' => 'Le champ %s ne peut contenir que des caractères alphanumeriques, des soulignés (underscore) et des tirets.',
	'numeric' => 'Le champ %s ne peut contenir que des nombres.',
	'is_numeric' => 'Le champ %s ne peut contenir que des caractères numériques.',
	'integer' => 'Le champ %s ne peut contenir qu\'un nombre entier.',
	'matches' => 'le champ %s ne correspond pas au champ %s.',
	'is_natural' => 'Le champ %s ne peut contenir que des nombres positifs.',
	'is_natural_no_zero' => 'Le champ %s ne peut contenir qu\'un nombre strictement supérieur à zéro.',
	'valid_ee_date' => 'La %s que vous avez soumise n\'était pas formattée correctement (année-mois-jour heure:minute)',
);


/* End of file safecracker_lang.php */
/* Location: ./system/expressionengine/third_party/safecracker/language/french/safecracker_lang.php */
